import icebear from "@pages/chatPage/icebear.jpeg";
import video from "@pages/chatPage/example.mp4";

export const dummyData = {
  totalCount: 21,
  nodes: [
    {
      id: 1,
      chatRoomId: 1,
      userId: "me",
      content: "안녕",
      attachment: {
        id: 1,
        type: "text",
        url: "",
        createdAt: "10:00",
      },
      createdAt: "10:00",
    },
    {
      id: 2,
      chatRoomId: 1,
      userId: null,
      content: "클레오파트라",
      attachment: {
        id: 2,
        type: "text",
        url: "",
        createdAt: "10:00",
      },
      createdAt: "10:00",
    },
    {
      id: 3,
      chatRoomId: 1,
      userId: "me",
      content: "세상에서 제일 가는",
      attachment: {
        id: 3,
        type: "text",
        url: "",
        createdAt: "10:00",
      },
      createdAt: "10:00",
    },
    {
      id: 4,
      chatRoomId: 1,
      userId: null,
      content: "포테이토칩",
      attachment: {
        id: 4,
        type: "text",
        url: "",
        createdAt: "10:00",
      },
      createdAt: "10:00",
    },
    {
      id: 5,
      chatRoomId: 1,
      userId: "me",
      content: "여기 이미지 예시입니다.",
      attachment: {
        id: 5,
        type: "image",
        url: icebear,
        createdAt: "10:00",
      },
      createdAt: "10:00",
    },
    {
      id: 6,
      chatRoomId: 1,
      userId: null,
      content: "여기 비디오 예시입니다.",
      attachment: {
        id: 6,
        type: "video",
        url: video,
        createdAt: "10:00",
      },
      createdAt: "10:00",
    },
    {
      id: 7,
      chatRoomId: 1,
      userId: "me",
      content: "안녕",
      attachment: {
        id: 7,
        type: "text",
        url: "",
        createdAt: "10:00",
      },
      createdAt: "10:00",
    },
    {
      id: 8,
      chatRoomId: 1,
      userId: null,
      content: "세상에서 제일 가는",
      attachment: {
        id: 8,
        type: "text",
        url: "",
        createdAt: "10:00",
      },
      createdAt: "10:00",
    },
    {
      id: 9,
      chatRoomId: 1,
      userId: null,
      content: "포테이토칩",
      attachment: {
        id: 9,
        type: "text",
        url: "",
        createdAt: "10:00",
      },
      createdAt: "10:00",
    },
  ],
};
